version: "3.7"

services:
  teamcity:
    image: jetbrains/teamcity-server
    volumes:
      - ./data-teamcity-server:/data/teamcity_server/datadir
      - ./data-teamcity-logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent
    build: ./agent
    environment:
      SERVER_URL: http://teamcity:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
