version: '3.1'

services:
  generator:
    # Note: "-10" means default to 10
    image: localhost:55000/gen:ci-${GENERATOR_BUILD_NUMBER-10}
    #ports:
    #  - "8080:80"
  mail:
    image: mailhog/mailhog
    #ports:
    #  - "8025:8025"
  integration:
    depends_on:
      - generator
    # Note: "-10" means default to 10
    image: localhost:55000/gen:integration-${BUILD_NUMBER-10}
    build: .
    environment:
      - TEAMCITY_PROJECT_NAME